name: Feature Request
description: Suggest a new feature for the Poseidon Platform
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true
  
  - type: dropdown
    id: service
    attributes:
      label: Affected Service
      options:
        - poseidon-current
        - poseidon-forge
        - poseidon-harbor
        - poseidon-lighthouse
        - poseidon-anchor
        - poseidon-depths
        - poseidon-tide
        - platform-wide
