site_name: Poseidon Platform
site_description: Enterprise Development Infrastructure - IC Portfolio & Case Study
site_author: IC Technical Leadership

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - tables
  - footnotes

nav:
  - Home: index.md
  - Platform:
    - Overview: platform/overview.md
    - Architecture: platform/architecture.md
  - Services:
    - Overview: services/index.md
    - poseidon-current:
      - Overview: services/current/overview.md
      - Architecture: services/current/architecture.md
      - Implementation: services/current/implementation.md
      - Testing: services/current/testing.md
    - poseidon-oracle:
      - Overview: services/oracle/overview.md
  - Engineering:
    - Decisions:
      - Overview: engineering/decisions/index.md
      - ADR-001 Microservices: engineering/decisions/adr-001-microservices.md
      - ADR-002 Testing Strategy: engineering/decisions/adr-002-testing-strategy.md
      - ADR-003 AI Integration: engineering/decisions/adr-003-ai-integration.md
      - ADR-004 Deployment Model: engineering/decisions/adr-004-deployment-model.md
  - Case Studies:
    - Development Workflow Automation: case-studies/development-acceleration.md
    - Integrated Quality Engineering: case-studies/quality-gates.md

# Adobe Brand Styling
extra_css:
  - assets/css/custom.css
